### PR TITLE
Good to be merged on master :)

### PR DESCRIPTION
**Pull request by diasdavid**
@fmjgomes @johnytiago wanna review? Lot's of stuff changed! Lot's of new goodies :)

### CODE REVIEW

**Comment by diasdavid** [comment]
(reviewing is where you open the diff view (https://github.com/lisbon-community/www/pull/2/files) and comment if you don't understand a piece or if something is wrong, just push a new commit to this branch. If everything looks look, comment with a +1 or a :+1: :)

**Comment by johnytiago** [comment]
Mt nice! ;) é suposto ser um de nós a dar merge?

**Comment by diasdavid** [comment]
Se sentires-te confiante, claro :) Não vale é dar merge sem fazer review :)

**Comment by johnytiago** [comment]
Ainda não vi bem o código, não vale a pena fazer coisas á maluca! ^^

**Comment by diasdavid** [comment]
@johnytiago @fmjgomes done this merge

**Pull request merged**
